### ISSUE TITLE
Block features for abuse

### ISSUE THREAD

**Issue by tuvs** [chayev/linkSimulator#6]
- [x] 1. Can we keep the params section but have a dropdown instaed of free text? (Ohad to ask Ram) (Remove unnecessary fields - adset, ad.
- [x] 2. Add number of fruit - (from 1 to 99) dropdown
- [x] 3. Redirection Params - change to drop downs - (apples, peaches, bananas, Appstore, Playstore)

**Comment by chayev** [comment]
@tuvs did you get details on 1 in the dropdown? what needs to be removed?

**Comment by tuvs** [comment]
Yes, Ram approved the change we want to do. 
the fields that needs to be removed - adset, ad
